export const url = (name: string, size: string) => {
  return `https://firebasestorage.googleapis.com/v0/b/portfolio-f1335.appspot.com/o/${name}-${size}.webp?alt=media`
}

export const works = [
  {
    title: 'Office Studio',
    technologies: ['HTML', 'CSS', 'JavaScript'],
    thumbnail: 'https://firebasestorage.googleapis.com/v0/b/portfolio-f1335.appspot.com/o/1-small.webp?alt=media',
    color: '#F8F8F8',
    href: '#',
  },
  {
    title: 'Modern',
    technologies: ['React', 'Tailwind', 'Django'],
    thumbnail: 'https://firebasestorage.googleapis.com/v0/b/portfolio-f1335.appspot.com/o/2-small.webp?alt=media',
    color: '#D200F8',
    href: '#',
  },
  {
    title: 'There',
    technologies: ['HTML', 'CSS', 'JavaScript'],
    thumbnail: 'https://firebasestorage.googleapis.com/v0/b/portfolio-f1335.appspot.com/o/3-small.webp?alt=media',
    color: '#1743DD',
    href: '#',
  },
  {
    title: 'Vintage',
    technologies: ['HTML', 'CSS', 'JavaScript'],
    thumbnail: 'https://firebasestorage.googleapis.com/v0/b/portfolio-f1335.appspot.com/o/4-small.webp?alt=media',
    color: '#A7A7D3',
    href: '#',
  },
  {
    title: 'Put',
    technologies: ['HTML', 'CSS', 'JavaScript'],
    thumbnail: 'https://firebasestorage.googleapis.com/v0/b/portfolio-f1335.appspot.com/o/preview-medium.webp?alt=media',
    color: '#BBAA22',
    href: '#',
  },
  {
    title: 'Bag',
    technologies: ['HTML', 'CSS', 'JavaScript'],
    thumbnail: 'https://firebasestorage.googleapis.com/v0/b/portfolio-f1335.appspot.com/o/preview-medium.webp?alt=media',
    color: '#B8B8AA',
    href: '#',
  },
  {
    title: 'Android Studio',
    technologies: ['React Native', 'Hono', 'Bun'],
    thumbnail: 'https://firebasestorage.googleapis.com/v0/b/portfolio-f1335.appspot.com/o/preview-medium.webp?alt=media',
    color: '#E0E0AB',
    href: '#',
  },
  {
    title: 'Apple Studio',
    technologies: ['Vue', 'Solid', 'Svelte'],
    thumbnail: 'https://firebasestorage.googleapis.com/v0/b/portfolio-f1335.appspot.com/o/preview-medium.webp?alt=media',
    color: '#CCDD71',
    href: '#',
  },
  {
    title: 'Office Studio',
    technologies: ['HTML', 'CSS', 'JavaScript'],
    thumbnail: 'https://firebasestorage.googleapis.com/v0/b/portfolio-f1335.appspot.com/o/preview-medium.webp?alt=media',
    color: '#F8F8F8',
    href: '#',
  },
  {
    title: 'Modern',
    technologies: ['React', 'Tailwind', 'Django'],
    thumbnail: 'images/img2.jpg',
    color: '#D200F8',
    href: '#',
  },
  {
    title: 'There',
    technologies: ['HTML', 'CSS', 'JavaScript'],
    thumbnail: 'images/img3.jpg',
    color: '#1743DD',
    href: '#',
  },
  {
    title: 'Vintage',
    technologies: ['HTML', 'CSS', 'JavaScript'],
    thumbnail: 'images/img4.jpg',
    color: '#A7A7D3',
    href: '#',
  },
  {
    title: 'Put',
    technologies: ['HTML', 'CSS', 'JavaScript'],
    thumbnail: 'images/img5.jpg',
    color: '#BBAA22',
    href: '#',
  },
  {
    title: 'Bag',
    technologies: ['HTML', 'CSS', 'JavaScript'],
    thumbnail: 'images/img6.jpg',
    color: '#B8B8AA',
    href: '#',
  },
  {
    title: 'Android Studio',
    technologies: ['React Native', 'Hono', 'Bun'],
    thumbnail: 'images/img7.jpg',
    color: '#E0E0AB',
    href: '#',
  },
  {
    title: 'Apple Studio',
    technologies: ['Vue', 'Solid', 'Svelte'],
    thumbnail: 'images/img8.jpg',
    color: '#CCDD71',
    href: '#',
  },
  {
    title: 'Office Studio',
    technologies: ['HTML', 'CSS', 'JavaScript'],
    thumbnail: 'images/img1.jpg',
    color: '#F8F8F8',
    href: '#',
  },
  {
    title: 'Modern',
    technologies: ['React', 'Tailwind', 'Django'],
    thumbnail: 'images/img2.jpg',
    color: '#D200F8',
    href: '#',
  },
  {
    title: 'There',
    technologies: ['HTML', 'CSS', 'JavaScript'],
    thumbnail: 'images/img3.jpg',
    color: '#1743DD',
    href: '#',
  },
  {
    title: 'Vintage',
    technologies: ['HTML', 'CSS', 'JavaScript'],
    thumbnail: 'images/img4.jpg',
    color: '#A7A7D3',
    href: '#',
  },
  {
    title: 'Put',
    technologies: ['HTML', 'CSS', 'JavaScript'],
    thumbnail: 'images/img5.jpg',
    color: '#BBAA22',
    href: '#',
  },
  {
    title: 'Bag',
    technologies: ['HTML', 'CSS', 'JavaScript'],
    thumbnail: 'images/img6.jpg',
    color: '#B8B8AA',
    href: '#',
  },
  {
    title: 'Android Studio',
    technologies: ['React Native', 'Hono', 'Bun'],
    thumbnail: 'images/img7.jpg',
    color: '#E0E0AB',
    href: '#',
  },
  {
    title: 'Apple Studio',
    technologies: ['Vue', 'Solid', 'Svelte'],
    thumbnail: 'images/img8.jpg',
    color: '#CCDD71',
    href: '#',
  },
  {
    title: 'Office Studio',
    technologies: ['HTML', 'CSS', 'JavaScript'],
    thumbnail: 'images/img1.jpg',
    color: '#F8F8F8',
    href: '#',
  },
  {
    title: 'Modern',
    technologies: ['React', 'Tailwind', 'Django'],
    thumbnail: 'images/img2.jpg',
    color: '#D200F8',
    href: '#',
  },
  {
    title: 'There',
    technologies: ['HTML', 'CSS', 'JavaScript'],
    thumbnail: 'images/img3.jpg',
    color: '#1743DD',
    href: '#',
  },
  {
    title: 'Vintage',
    technologies: ['HTML', 'CSS', 'JavaScript'],
    thumbnail: 'images/img4.jpg',
    color: '#A7A7D3',
    href: '#',
  },
  {
    title: 'Put',
    technologies: ['HTML', 'CSS', 'JavaScript'],
    thumbnail: 'images/img5.jpg',
    color: '#BBAA22',
    href: '#',
  },
  {
    title: 'Bag',
    technologies: ['HTML', 'CSS', 'JavaScript'],
    thumbnail: 'images/img6.jpg',
    color: '#B8B8AA',
    href: '#',
  },
  {
    title: 'Android Studio',
    technologies: ['React Native', 'Hono', 'Bun'],
    thumbnail: 'images/img7.jpg',
    color: '#E0E0AB',
    href: '#',
  },
  {
    title: 'Apple Studio',
    technologies: ['Vue', 'Solid', 'Svelte'],
    thumbnail: 'images/img8.jpg',
    color: '#CCDD71',
    href: '#',
  },
]
