import '@/shared/css/global.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Footer, Navbar, LenisProvider } from '@/shared/components'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  icons: { icon: '/icons/favicon.svg' },
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning
        className={inter.className}
      >
        <LenisProvider>
          <div className="main__container">
            <Navbar />

            {children}

            <Footer />
          </div>
        </LenisProvider>
      </body>
    </html>
  )
}
